QUERY_REWRITE_PROMPT = """You are a financial research assistant specializing in SEC filings (10-K, 10-Q).
Rewrite the user's question to be more specific and better suited for semantic search in financial documents.

Rules:
- Expand ALL financial abbreviations and jargon into full descriptive terms:
  * ROC/ROIC → return on invested capital, net income, total equity, total debt, invested capital
  * ROE → return on equity, net income, shareholders equity
  * ROA → return on assets, net income, total assets
  * EPS → earnings per share, net income, weighted average shares
  * P/E → price earnings ratio, net income, shares outstanding
  * ROI → return on investment, net income, total assets
  * EBITDA → earnings before interest taxes depreciation amortization, operating income
  * Gross margin → gross margin, total net sales, cost of sales
  * Operating margin → operating margin, operating income, total net sales
  * Net margin / profit margin → net margin, net income, total net sales
  * Revenue → total net sales, products, services
  * Free cash flow → free cash flow, cash generated by operating activities, capital expenditures
- If the question is about a financial ratio or metric, explicitly mention the COMPONENTS needed to calculate it (e.g., for ROC mention "net income", "total equity", "total debt", "invested capital")
- Add financial context (e.g., specify fiscal year, unit like "millions/billions of USD")
- If the question is in Chinese, rewrite into English with full financial term expansion
- Include synonyms: e.g., "net income OR net profit OR net earnings"
- Keep the original intent but make it maximally searchable

Original question: {question}

Rewritten question:"""

METADATA_EXTRACTION_PROMPT = """Extract financial metadata from this question. Identify:
1. All company names mentioned (lowercase, e.g. "apple", "microsoft", "nvidia", "tesla"). Use a list even if only one company.
2. The fiscal year (4-digit string, e.g. "2023")
3. The quarter if mentioned (e.g. "Q1", "Q2", "Q3", "Q4", or empty string for annual)

Question: {question}

Respond in JSON format: {{"company_names": ["apple", "nvidia"], "year": "...", "quarter": "..."}}"""

ANSWER_GENERATION_PROMPT = """You are an expert financial analyst. Answer the question based ONLY on the provided document excerpts from a company's SEC filing.

Rules:
- Use specific numbers and facts from the documents
- Cite your sources using [Page X] notation
- If the documents don't contain enough information to fully answer, say clearly what data IS available and what is missing
- For financial ratios or calculations, show the formula and the data you used
- Cross-reference multiple document excerpts if needed (e.g., get net income from the income statement AND total assets from the balance sheet)
- Use markdown formatting for clarity (tables, bold, etc.)
- Always specify units (millions/billions of USD, percentages, etc.)
- If you can find SOME of the data needed for a calculation but not all, report what you found and explain what's missing

Question: {question}

Document excerpts:
{documents}

Provide a comprehensive answer with citations:"""

FINANCIAL_DATA_EXTRACTION_PROMPT = """Extract key financial metrics from these document excerpts from a company's financial report.

Extract the following metrics for each year/period mentioned:
- Revenue (total net sales)
- Net income
- Gross margin (% or absolute)
- Earnings per share (EPS)
- Total assets
- Total liabilities
- Operating income

Document excerpts:
{documents}

Respond in JSON format:
{{
  "company_name": "...",
  "data_points": [
    {{
      "year": 2023,
      "revenue_millions": null,
      "net_income_millions": null,
      "gross_margin_pct": null,
      "eps": null,
      "total_assets_millions": null,
      "operating_income_millions": null
    }}
  ]
}}

Only include fields where you have actual data. Use null for missing values."""

CHART_DATA_EXTRACTION_PROMPT = """You are a financial data extraction expert. Based on the user's question and the document excerpts, determine if a chart should be generated and extract structured data if so.

Generate a chart ONLY when ALL conditions are met:
- The question involves financial data (revenue, income, margins, ratios, etc.)
- The data contains multiple time periods, multiple metrics, or comparison across categories
- There are at least 2 data points available

Do NOT generate a chart when:
- Asking about a single year and single metric (e.g., "What is Apple's 2025 revenue?")
- Non-financial questions (e.g., "Who is the CEO?")
- Not enough data points in the documents

Question: {question}

Document excerpts:
{documents}

Respond in JSON format only (no markdown, no explanation):
If chart needed:
{{"need_chart": true, "chart_type": "bar", "title": "Chart Title", "x_key": "year", "data": [{{"year": "2023", "metric1": 100, "metric2": 50}}], "series": [{{"key": "metric1", "name": "Metric 1", "color": "#3b82f6"}}, {{"key": "metric2", "name": "Metric 2", "color": "#10b981"}}]}}

Use "line" for trend over time, "bar" for comparisons.
Colors: #3b82f6 (blue), #10b981 (green), #f59e0b (amber), #ef4444 (red), #8b5cf6 (purple), #ec4899 (pink).
Keep values as numbers (millions/billions, no currency symbols). Use concise series names.

If no chart needed:
{{"need_chart": false}}"""
